- launch/mongo-to-s3.yml
refer to ticket for full context: https://clever.atlassian.net/browse/IPOC-982
> autoscaling params

- main.go
This reverts commit fc436fa79c6f979b174207356f2a58752d7739bd.
Seems like this breaks the sync in some way. Needs more investigation.
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> Revert "Only request the desired fields from the mongo db."

- Gopkg.lock
- Gopkg.toml
- main.go
**JIRA:**
https://clever.atlassian.net/browse/IP-2113
**Overview:**
**Testing:**
**Roll Out:**
> Migrate to using analyticsutil.analyticspipeline for config.

- Makefile
- launch/mongo-to-s3.yml
- main.go
To support https://github.com/Clever/ark-config/pull/1587
> add LEGACY_CONFIG env var

- main.go
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> Fix conf path issues.

- Gopkg.lock
- Gopkg.toml
- Makefile
- launch/mongo-to-s3.yml
- main.go
- main_test.go
**JIRA:** [IPOC-1141](https://clever.atlassian.net/browse/IPOC-1141)
**Overview:**
The IL managed Mongo DB has been done away with even sooner than I expected, so all jobs pulling from that have started failing and we must migrate. This necessitates more changes than expected due to the managed db not requiring authentication and this worker not supporting it. The database URL is moving from the payload to the config.
Associated ark-config PR: https://github.com/Clever/ark-config/pull/1764
**Testing:** Updated the tests, plan on testing in dev.
**Roll Out:**
> IPOC-1141: migrate to IL Atlas

- Makefile
- main.go
**JIRA:** https://clever.atlassian.net/browse/DISC-936
**Overview:**
- adding misc data source for appUniverse
- config vars are already in use
**Testing:**
**Roll Out:**
> adding new mongo source: misc

- Gopkg.lock
- Gopkg.toml
- launch/mongo-to-s3.yml
- main.go
**JIRA:**
https://clever.atlassian.net/browse/DEIP-171
**Overview:**
Hot on the tail of https://github.com/Clever/connections-to-s3/pull/104
Now that it works, we can add debouncing to other services.
**Testing:**
**Roll Out:**
Dependent on https://github.com/Clever/s3-to-redshift/pull/169
> Now with job debouncing.

- main.go
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> Change flag case.

- main.go
> s3-to-redshift requires a date

- launch/mongo-to-s3.yml
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> Rename eng-ip to eng-deip

- Dockerfile
- launch/mongo-to-s3.yml
This PR is the second step in migrating this worker to pods
To check before merging
- If this worker has elastic ip(s) associated then close this PR and contact oncall-infra
- if this app uses outgoing ips i.e the customer or vendor whitelists clever IPs so that this app can connect to their resources then do not migrate this app and contact #oncall-infra
This PR will
- deploy the prod version of the worker to pods
After the steps below this worker will be doing approximately 50% of the work from the pod deployment in prod
After merging this PR once the deploy is complete
1. Verify deploy was succesful and that there were no container exits. This can be done by looking at container count in grafana (go/workers)
In case of errors
1. revert this PR
2. merge the deploy
3. `ark start …
> adjust resources and set to podOnly

- Dockerfile
- launch/mongo-to-s3.yml
> Revert "adjust resources and set to podOnly"

- Dockerfile
- launch/mongo-to-s3.yml
> Revert "Revert "adjust resources and set to podOnly""

- launch/mongo-to-s3.yml
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> Prod back to homepod for testing

- launch/mongo-to-s3.yml
Seems like jobs are running in dev podOnly ok... trying with prod again to see what happens
https://github.com/Clever/ark-config/pull/3533/files
> Prod to podOnly

- launch/mongo-to-s3.yml
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> no homepod

- launch/mongo-to-s3.yml
**JIRA:**
**Overview:**
**Testing:**
**Roll Out:**
> revert pod for prod again

- launch/mongo-to-s3.yml
- main.go
**JIRA:**
https://clever.atlassian.net/browse/IPOC-1660
**Overview:**
This PR changes mongo-to-s3 to use the Nearest read pref for mongo: https://docs.mongodb.com/manual/core/read-preference-use-cases/#std-label-read-preference-use-cases
Config changes: https://github.com/Clever/ark-config/pull/3537
**Testing:**
I tested this on Clever dev and it seems like it it able to run for much longer without being killed (the first two failures are due to the flare about IAM shortly after deployment I think, and are unrelated)
https://clever-dev--hubble--skylark.int.clever.com/mongo-to-s3:master/workflows/w/4ca0d2e0-2546-41c3-bbdb-7ae841b33c29/jobs
Previously jobs would die in <10 minutes ex.
https://clever-dev--hubble--skylark.int.clever.com/mongo-to-s3:master/workflows/w/ef915f56-712e-4d91-86f5-a8 …
> Try to fix errors

- launch/mongo-to-s3.yml
Same as https://github.com/Clever/matchmaker-spawner/pull/39
> update pod_config.group to reduce cross region dependencies
